/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Chatbox: typeof import('./src/components/Chatbox.vue')['default']
    ChatboxHello: typeof import('./src/components/ChatboxHello.vue')['default']
    ChatboxMarkdownContent: typeof import('./src/components/ChatboxMarkdownContent.vue')['default']
    ChatboxReactPosts: typeof import('./src/components/ChatboxReactPosts.vue')['default']
    ChatInput: typeof import('./src/components/ChatInput.vue')['default']
    ConfirmPopup: typeof import('primevue/confirmpopup')['default']
    Dialog: typeof import('primevue/dialog')['default']
    FloatColorModeButton: typeof import('./src/components/FloatColorModeButton.vue')['default']
    FloatIconButton: typeof import('./src/components/FloatIconButton.vue')['default']
    FloatThreadConfigButton: typeof import('./src/components/FloatThreadConfigButton.vue')['default']
    FormField: typeof import('@primevue/forms/formfield')['default']
    FormItem: typeof import('./src/components/FormItem.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Select: typeof import('primevue/select')['default']
    SettingModel: typeof import('./src/components/SettingModel.vue')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
